### ISSUE TITLE
Login with google, token is null.

### ISSUE THREAD

**Issue by fukhaos** [RogaLabs/social-login#10]
When I login with Google+
the token is always null
using version 1.2.1

![captura de tela 2017-03-30 as 09 26 36](https://cloud.githubusercontent.com/assets/1226155/24504039/070ba6d2-152b-11e7-8d73-eee2341eb920.png)

**Comment by singhdd93** [comment]
Same Here. Getting token null while other values are fine

**Comment by cleylsonsouza** [comment]
The last version has the token information now.
