### ISSUE TITLE
Error:(2, 0) Plugin with id 'kotlin-android' not found.

### ISSUE THREAD

**Issue by patelanil2007** [RogaLabs/social-login#5]
Error:(2, 0) Plugin with id 'kotlin-android' not found.
<a href="openFile:D:\optnbuy.com\Optnbuy\lib\build.gradle">Open File</a>

**Comment by cleylsonsouza** [comment]
I think you must install Kotlin plugin on your Android Studio.
https://blog.jetbrains.com/kotlin/2013/08/working-with-kotlin-in-android-studio/
